/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_api_v1_students_get"];
        put?: never;
        /** Create Student */
        post: operations["create_student_api_v1_students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student */
        get: operations["get_student_api_v1_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Student */
        patch: operations["update_student_api_v1_students__student_id__patch"];
        trace?: never;
    };
    "/api/v1/students/{student_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ledger */
        get: operations["get_ledger_api_v1_students__student_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{student_id}/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Drift */
        get: operations["get_drift_api_v1_students__student_id__drift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{student_id}/ledger.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ledger Pdf */
        get: operations["get_ledger_pdf_api_v1_students__student_id__ledger_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{student_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Payment */
        post: operations["record_payment_api_v1_students__student_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{student_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Override */
        post: operations["create_override_api_v1_students__student_id__overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly Report */
        get: operations["monthly_report_api_v1_reports_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/monthly.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly Report Pdf */
        get: operations["monthly_report_pdf_api_v1_reports_monthly_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DashboardSummaryOut */
        DashboardSummaryOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Total Collected This Month */
            total_collected_this_month: string;
            /** Total Outstanding */
            total_outstanding: string;
            /** Top Latecomers */
            top_latecomers: components["schemas"]["LatecomerOut"][];
        };
        /** DriftOut */
        DriftOut: {
            /** Student Id */
            student_id: number;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Cumulative Drift */
            cumulative_drift: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatecomerOut */
        LatecomerOut: {
            /** Student Id */
            student_id: number;
            /** Name */
            name: string;
            /** Cumulative Drift */
            cumulative_drift: number;
        };
        /** LedgerEntryOut */
        LedgerEntryOut: {
            /** Cycle Number */
            cycle_number: number;
            /**
             * Expected Due Date
             * Format: date
             */
            expected_due_date: string;
            /** Paid Date */
            paid_date: string | null;
            /** Days Late */
            days_late: number | null;
            /** Amount */
            amount: string | null;
            /** Cumulative Drift */
            cumulative_drift: number;
        };
        /** LedgerOut */
        LedgerOut: {
            /** Student Id */
            student_id: number;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Cumulative Drift */
            cumulative_drift: number;
            /** Entries */
            entries: components["schemas"]["LedgerEntryOut"][];
        };
        /** MonthlyReportOut */
        MonthlyReportOut: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Total Collected */
            total_collected: string;
            /** Total Outstanding */
            total_outstanding: string;
            /** Rows */
            rows: components["schemas"]["MonthlyReportRowOut"][];
        };
        /** MonthlyReportRowOut */
        MonthlyReportRowOut: {
            /** Student Id */
            student_id: number;
            /** Name */
            name: string;
            status: components["schemas"]["StudentStatus"];
            /** Fee */
            fee: string;
            /** Collected */
            collected: string;
            /** Cumulative Drift */
            cumulative_drift: number;
            /** Outstanding */
            outstanding: string;
        };
        /** OverrideCreate */
        OverrideCreate: {
            /**
             * New Due Date
             * Format: date
             */
            new_due_date: string;
            /** Reason */
            reason: string;
        };
        /** OverrideOut */
        OverrideOut: {
            /** Id */
            id: number;
            /** Student Id */
            student_id: number;
            /**
             * New Due Date
             * Format: date
             */
            new_due_date: string;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PaymentCreate */
        PaymentCreate: {
            /**
             * Paid Date
             * Format: date
             */
            paid_date: string;
            /** Amount */
            amount: number | string;
            /** Cycle Number */
            cycle_number?: number | null;
            /**
             * For Month
             * @description Which month it settles, YYYY-MM
             */
            for_month?: string | null;
        };
        /** PaymentOut */
        PaymentOut: {
            /** Id */
            id: number;
            /** Student Id */
            student_id: number;
            /** Cycle Number */
            cycle_number: number;
            /**
             * Paid Date
             * Format: date
             */
            paid_date: string;
            /**
             * Expected Due Date
             * Format: date
             */
            expected_due_date: string;
            /** Days Late */
            days_late: number;
            /** Amount */
            amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StudentCreate */
        StudentCreate: {
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /**
             * Join Date
             * Format: date
             */
            join_date: string;
            /** Fee */
            fee: number | string;
            /** @default active */
            status: components["schemas"]["StudentStatus"];
        };
        /** StudentDetailOut */
        StudentDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /**
             * Join Date
             * Format: date
             */
            join_date: string;
            /** Fee */
            fee: string;
            status: components["schemas"]["StudentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cumulative Drift */
            cumulative_drift: number;
            /** Months Overdue */
            months_overdue: number;
            /**
             * Next Expected Date
             * Format: date
             */
            next_expected_date: string;
            /** Payments Count */
            payments_count: number;
            /** Total Paid */
            total_paid: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
        };
        /** StudentListItemOut */
        StudentListItemOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /**
             * Join Date
             * Format: date
             */
            join_date: string;
            /** Fee */
            fee: string;
            status: components["schemas"]["StudentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cumulative Drift */
            cumulative_drift: number;
            /** Months Overdue */
            months_overdue: number;
        };
        /** StudentOut */
        StudentOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /**
             * Join Date
             * Format: date
             */
            join_date: string;
            /** Fee */
            fee: string;
            status: components["schemas"]["StudentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * StudentSort
         * @enum {string}
         */
        StudentSort: "drift_desc";
        /**
         * StudentStatus
         * @description Whether a student is currently attending.
         * @enum {string}
         */
        StudentStatus: "active" | "inactive";
        /** StudentUpdate */
        StudentUpdate: {
            /** Phone */
            phone?: string | null;
            /** Fee */
            fee?: number | string | null;
            status?: components["schemas"]["StudentStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_students_api_v1_students_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["StudentStatus"] | null;
                sort?: components["schemas"]["StudentSort"] | null;
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentListItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_student_api_v1_students_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_api_v1_students__student_id__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_student_api_v1_students__student_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ledger_api_v1_students__student_id__ledger_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_drift_api_v1_students__student_id__drift_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ledger_pdf_api_v1_students__student_id__ledger_pdf_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                /** @description Force a locale (en/fr); overrides Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_payment_api_v1_students__student_id__payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_override_api_v1_students__student_id__overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_report_api_v1_reports_monthly_get: {
        parameters: {
            query: {
                year: number;
                month: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_report_pdf_api_v1_reports_monthly_pdf_get: {
        parameters: {
            query: {
                year: number;
                month: number;
                /** @description Force a locale (en/fr); overrides Accept-Language. */
                lang?: string | null;
            };
            header?: {
                "accept-language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
