"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-23 11:48:23.097493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='studentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('fee >= 0', name='ck_student_fee_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anchor_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(trim(reason)) > 0', name='ck_anchor_override_reason_nonempty'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('expected_due_date', sa.Date(), nullable=False),
    sa.Column('days_late', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_payment_amount_non_negative'),
    sa.CheckConstraint('cycle_number >= 0', name='ck_payment_cycle_number_non_negative'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'cycle_number', name='uq_payment_student_cycle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('anchor_override')
    op.drop_table('student')
    # ### end Alembic commands ###
